export const images = {
  logo: { src: '/assets/logo.svg', alt: 'logo', width: 56, height: 90 },
  logo3: { src: '/assets/logo3.svg', alt: 'logo3', width: 135, height: 42 },
  menuIcon: { src: '/assets/menu.svg', alt: 'menu icon', width: 20, height: 20 },
  footerBackground: {
    src: '/assets/footer.png',
    alt: 'footer background',
    width: 1437,
    height: 233,
  },
  arrow: { src: '/assets/genie/benefits/arrow.svg', alt: 'arrow', width: 22, height: 22 },
  grayBulb: { src: '/assets/genie/benefits/grayBulb.svg', alt: 'gray bulb', width: 22, height: 22 },
  whiteBulb: {
    src: '/assets/genie/benefits/whiteBulb.svg',
    alt: 'white bulb',
    width: 22,
    height: 22,
  },
  grayFlag: { src: '/assets/genie/benefits/grayFlag.svg', alt: 'gray flag', width: 22, height: 22 },
  whiteFlag: {
    src: '/assets/genie/benefits/whiteFlag.svg',
    alt: 'white flag',
    width: 22,
    height: 22,
  },
  grayBag: { src: '/assets/genie/benefits/grayBag.svg', alt: 'gray bag', width: 22, height: 22 },
  whiteBag: { src: '/assets/genie/benefits/whiteBag.svg', alt: 'white bag', width: 22, height: 22 },
  grayStar: { src: '/assets/genie/benefits/grayStar.svg', alt: 'gray star', width: 22, height: 22 },
  whiteStar: {
    src: '/assets/genie/benefits/whiteStar.svg',
    alt: 'white star',
    width: 22,
    height: 22,
  },
};
