import type { Metadata } from "next";
import "./globals.css";
import SmoothScrolling from "@/components/common/lenis";
import { GoogleReCaptchaProvider } from 'react-google-recaptcha-v3';

export const metadata: Metadata = {
  title: "Servgenie",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/assets/favicon.svg" type="image/svg+xml" />
      </head>
      <body className="overflow-x-hidden">
        <SmoothScrolling >
          {children}
        </SmoothScrolling>
      </body>
    </html>
  );
}
