import type { Metadata } from "next";
import { ReactLenis } from '@/utils/lenis';
import Navbar from "@/components/GenieComponents/Navbar";

export const metadata: Metadata = {
    title: "Servgenie",
    description: "Generated by create next app",
};

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Navbar />
            {children}
        </>
    );
}
